[package]
name = "quadit"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = "4.4.18"
env_logger = "^0.10.2"
gitsync = "0.1.9"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
serde_yaml = "0.9.30"
