configReload:
  configURL: https://raw.githubusercontent.com/ubiquitous-factory/quadit/main/samples/config.yaml
  schedule: "1/120 * * * * *"
targetConfigs:
- url: https://github.com/ubiquitous-factory/quadit
  targetPath: "sleep.container"
  branch: "main"
  schedule: "1/2 * * * * *"